<template>
    <PageWrapper layout="boxed">
        <div class="document bg-gray-900 rounded border-gray-alt2 border max-w-4xl m-auto">
            <h1 class="p-8 dm-sans capitalize text-white text-2xl leading-none">Website Terms of Use Agreement</h1>
            <hr>
            <div class="p-8">
                <p>Please carefully read these terms and conditions of use (these "Terms of Use") before using this website (the "Website"). Your access to and use of this Website is subject to these Terms of Use (including the Privacy Policy of the Website) and all applicable laws. By accessing and using this Website, you signify your assent to these Terms of Use. These Terms of Use may be amended or modified at the sole discretion of website owner, or new conditions may be imposed, at any time with or without notice. Any such changes or additions will be reflected by an update of this posting. Please check these Terms of Use periodically for changes. Your continued use of the Website following the posting of changes to these Terms of Use (including the Privacy Policy) will mean you accept those changes. Your access to and use of other Vixory products and services may be governed by separate terms and conditions. If you do not agree to these Terms of Use, please do not use the Website.</p>
                
                <h2>1. Website Ownership; Use of Website; Content</h2>
                <p>The Website is owned by Vixory LLC and operated by the Vixory LLC. Vixory LLC, its subsidiaries, dbas, employees, agents, officers, directors and owners shall be referred to herein as “Vixory”. Vixory and its respective operators, affiliates, employees, directors and officers shall be collectively referred to herein as the "Operators." All materials distributed in the Website (the "Materials") are either owned by or licensed to Vixory. Vixory, along with their licensors, retain all proprietary rights to the Materials. Except for downloading one copy of the Materials on any single computer for your personal, non-commercial home use, you must not reproduce, prepare derivative works based upon, distribute, perform or display the Materials without first obtaining the written permission of Vixory. Materials must not be used in any unauthorized manner.</p>
                <p>Subject to the terms and conditions of this Agreement, you are hereby granted a non-exclusive, limited, non-transferable, freely revocable license to use the Website. Vixory reserves all rights not expressly granted herein the Website and Content (as defined below) provided by Vixory or its licensors. Vixory may terminate this license at any time for any reason or no reason.</p>
                <p>All right, title, and interest in and to the Website (excluding Content provided by you) are and will remain the exclusive property of Vixory and its licensors. The Website is protected by copyright, trademark, and other laws of the United States and foreign countries. Nothing in this Agreement gives you a right to use the Vixory name or any Vixory trademarks, logos, domain names, or other distinctive brand features, or those of any Vixory licensor. Any feedback, comments, or suggestions you may provide regarding Vixory or the Website are entirely voluntary, and we will be free to use such feedback, comments, or suggestions as we see fit and without any obligation to you.</p>
                <p>You are responsible for safeguarding any password that you may use to access the Website and for any activities occurring or actions taken under your password. We encourage you to use “strong” passwords (passwords that use a combination of upper and lower case letters, numbers, and symbols) with your account. Vixory will not be liable for any loss or damage arising from your failure to comply with these recommendations. By connecting to Vixory with a third-party service, you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials and other data received from that service. By providing Vixory with your email address you consent to our using the email address to send you Website-related notices, including any notices required by law, in lieu of communication by postal mail.</p>
                <p>We may, without prior notice, change the Website; stop providing the Website or features of the Website to you or to users generally; or create usage limits for the Website.</p>
                <p>You must not do any of the following while accessing or using the Website: (i) use the Website for any unlawful purposes or for promotion of illegal activities; (ii) post any Content or use the Website in violation of any applicable law (including intellectual property laws, right of privacy or publicity laws, and any laws of a non-U.S. jurisdiction applicable to you), or any contractual or other legal obligation; (iii) post Content that is hateful, abusive, threatening, profane, or that you know to be incorrect, misleading, or deceptive; (iv) publish or post other people's private or personally identifiable information without their express authorization; (v) publish or link to malicious content intended to damage or disrupt another user's browser or computer or to compromise a user’s privacy; (vi) access or tamper with non-public areas of the Website, Vixory's computer systems, or the technical delivery systems of Vixory's providers; (vii) probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures; (viii) access or search or attempt to access or search the Website by any means (automated or otherwise) other than through the currently available, published interfaces that are provided by Vixory, unless you have been specifically allowed to do so in a separate agreement with Vixory; or (ix) interfere with or disrupt (or attempt to do so) the access of any user, host or network, including, without limitation, by sending a virus, overloading, flooding, spamming, or mail-bombing the Website.</p>
                <p>Vixory may investigate and/or suspend your account or access to the Website if you violate any of the above policies. Vixory reserves the right to immediately terminate your account or access to the Website without further notice in the event that, in its judgment, you violate this Agreement.</p>
                
                <p class="font-bold">Your Content</p>
                <p>"Content" means any information, text, graphics, or other materials uploaded, downloaded or appearing on the Website. You retain ownership of all Content you submit, post, display, or otherwise make available on the Website.</p>
                <p>By submitting, posting or displaying Content on or through the Website, you grant, and you represent and warrant that you have a right to grant, to Vixory a worldwide, non-exclusive, perpetual, royalty-free license (with the right to sublicense) to use, reproduce, adapt, modify, publish, transmit, perform, display, distribute, and make derivative works of such Content in any and all media or distribution methods (now known or later developed). You agree that this license includes the right for Vixory to make your Content available to others for the publication, distribution, syndication, or broadcast of such Content on other media and services.</p>
                <p>Your content will be able to be viewed by other users of the Website and through third party services and websites. You should only provide Content that you are comfortable sharing with others under the terms of this Agreement. All Content, whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such Content. We may not monitor or control the Content posted via the Website. We do not endorse, support, represent or guarantee the completeness, truthfulness, accuracy, or reliability of any third party Content or communications posted via the Website nor does Vixory endorse any opinions expressed by third parties via the Website. Any use of or reliance on any Content or materials posted via the Website or obtained by you through the Website is at your own risk. You understand that by using the Website, you may be exposed to Content that might be offensive, harmful, inaccurate or otherwise inappropriate, or postings that have been mislabeled or are otherwise deceptive. Under no circumstances will Vixory be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the Website or broadcast elsewhere.</p>
                <p>You are responsible for your use of the Website, for any Content you provide, and for any consequences thereof, including the use of your Content by other users and third parties. You understand that your Content will be published on the Website and may be republished, and if you do not have the right to submit Content for such use, it may subject you to liability. Vixory will not be responsible or liable for any use of your Content by Vixory in accordance with this Agreement. You represent and warrant that you have all the rights, power and authority necessary to grant the rights granted herein to any Content that you submit and that Vixory’s use of your Content in accordance with this Agreement will not violate any law or infringe the rights of any third party.</p>
                <p>The Website may include advertisements, which may be targeted to the Content or information on the Website, or other information. In consideration for Vixory granting you access to and use of the Website, you agree that Vixory and its third party providers and partners may place such advertising on the Website or in connection with the display of Content or information from the Website whether submitted by you or others.</p>
                <p>We reserve the right at all times (but will not have an obligation) to remove or refuse to distribute any Content on the Website and to terminate your access.</p>
                
                <h2>2. Message Features</h2>
                <ul>
                    <li>Participation. The Website may offer opportunities for you to transmit messages in connection with various features which may include email, blogs, chats and message boards ("Message Features"). You must use Message Features in a responsible manner, and are solely responsible for any content you transmit. You must not transmit any message ("Message") in connection with any Message Feature that: (i) imposes an unreasonable or disproportionately large load on the Website's infrastructure, or otherwise adversely affects, restricts or inhibits any other user from using and enjoying the Website; (ii) is threatening, abusive, libelous, defamatory, obscene, vulgar, offensive, pornographic, profane, sexually explicit or indecent; (iii) constitutes or encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any local, state, national or international law; (iv) violates, plagiarizes or infringes the rights of third parties including, without limitation, copyright, trademark, patent, rights of privacy or publicity or any other proprietary right; (v) contains a virus or other harmful component; (vi) contains any information, software or other material of a commercial nature; (vii) contains advertising, promotions or commercial solicitations of any kind; (viii) constitutes or contains false or misleading indications of origin or statements of fact; (ix) contains material irrelevant to the subject matter of the Message Feature; or (x) contains any virus, trojan horse, worm, time bomb, cancelbot or other similar harmful or deleterious programming routine.</li>
                    <li>In order to participate in any Message Feature, you may be asked to register by providing certain personal information such as your name and/or email address. (The Website's Privacy Policy explains how such information may be collected and used.) You may also be asked select a screen name ("Screen Name") for identification purposes. You must not use any Screen Name that violates any term of subsections (i)-(x) above, or any other operating term set forth by Vixory.</li>
                    <li>License. By transmitting any Message or Screen Name, you are granting the Operators a perpetual, royalty-free, non-exclusive, and irrevocable right and license to reproduce, prepare derivative works based upon, distribute, perform or display such Message or Screen Name, in whole or in part, in any form, media or technology known or hereafter developed.</li>
                    <li>Message and Screen Name Review. The Operators and their vendors act as a passive conduit in connection with your use of Message Features. The Operators and their vendors have the right, but not the obligation, to review, edit or delete any Message or Screen Name transmitted by you that they believe may create a liability for them, and also to deny access to any Message Feature. Display of any Message or Screen Name in any Message Feature does not constitute its approval or endorsement by the Operators or their vendors.</li>
                    <li>You acknowledge that Messages and Screen Names are not confidential and they may be read, intercepted by others and widely accessible on the World Wide Web. You acknowledge that by submitting Messages to this Website, no confidential, fiduciary, contractually implied or other relationship is created between you and the Operators and their vendors other than as expressly set forth in this Agreement.</li>
                </ul>

                <h2>3. Operators</h2>
                <p>The Operators may change, suspend or discontinue any aspect of the Website at any time, including the availability of any Website feature, database, or content. The Operators may also impose limits on certain features and services or restrict your access to parts or the entire Website without notice or liability.</p>
            
                <h2>4. Votes; Contests; Sweepstakes</h2>
                <ul>
                    <li>The Website may offer you opportunities to vote in connection with certain events including and also to enter contests and sweepstakes. By participating in any such event, you signify your agreement to all special terms set forth on the Website applicable to the event as well as the terms of this Agreement.</li>
                </ul>

                <h2>5. Linking</h2>
                <ul>
                    <li>The Website may contain links and pointers to other World Wide Web sites and resources, including but not limited to, third party vendors. Links to and from the Website to other Web sites maintained by third parties, do not constitute an endorsement by the Operators or any of their affiliates of any third party Web site or content. The Operators are not responsible for the availability of these third party resources or their contents. You should direct any concerns regarding any external link to its Web site administrator or Webmaster.</li>
                </ul>

                <h2>6. Disclaimer of Warranties</h2>
                <ul>
                    <li>A. USE OF THE WEBSITE IS AT YOUR EXCLUSIVE RISK, AND THE RISK OF INJURY FROM THE FOREGOING RESTS EXCLUSIVELY WITH YOU.</li>
                    <li>B. THE WEBSITE, IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO ANY WARRANTIES OF TITLE OR WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</li>
                    <li>C. THE OPERATORS DO NOT WARRANT THAT: (1) THE WEBSITE WILL BE UNINTERRUPTED OR ERROR FREE; (2) DEFECTS OR ERRORS IN THE WEBSITEWILL BE CORRECTED; (3) THE WEBSITEWILL BE FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS; OR (4) ANY INFORMATION CONTAINED IN THE WEBSITE WILL BE ACCURATE OR RELIABLE.</li>
                </ul>

                <h2>7. Limitations on Liability</h2>
                <ul>
                    <li>A. NOTWITHSTANDING ANY TERM IN THIS AGREEMENT, OTHER OPERATING TERM SET FORTH BY THE OPERATORS OR ANY ACT OR FAILURE TO ACT BY THE OPERATORS, YOU ARE EXCLUSIVELY LIABLE FOR THE CONTENT OF EVERY MESSAGE AND SCREEN NAME YOU TRANSMIT VIA THE WEBSITE.</li>
                    <li>B. IN NO EVENT SHALL THE OPERATORS BE LIABLE FOR ANY BREACH IN TRANSACTION SECURITY CAUSED BY A THIRD PARTY ARISING OUT OF OR RELATING TO ANY ATTEMPT TO PURCHASE SERVICES OR MERCHANDISE.</li>
                    <li>C. IN NO EVENT SHALL THE OPERATORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR RELATING TO USE OF OR INABILITY TO USE THE WEBSITE. THIS LIMITATION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF THE OPERATORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, THE LIABILITY OF THE OPERATORS IN SUCH JURISDICTIONS SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW. THE MAXIMUM LIABILITY OF THE OPERATORS FOR ANY CLAIM ARISING OUT OF OR IN CONNECTION WITH THIS WEBSITE IS $50.</li>
                    <li>D. IN NO EVENT SHALL THE OPERATORS BE LIABLE FOR ANY FAILURE, INTERRUPTION OR ERROR WITH RESPECT TO ANY ASPECT OF THE WEBSITE, INCLUDING THE AVAILABILITY OF ANY SITE FEATURE.</li>
                </ul>

                <h2>8. Indemnification</h2>
                <p>You hereby agree to indemnify and hold the Operators and their respective members, shareholders, directors, officers, employees, agents and representatives harmless from all claims, liabilities, damages and expenses (including attorneys' fees and expenses) arising out of or relating to: (A) your use of the Website; or (B) any alleged breach of this Agreement by you.</p>

                <h2>9. Termination</h2>
                <p>The Operators may change, suspend or discontinue any aspect of the Website at any time, including the availability of any Website feature, database, or content. The Operators may also impose limits on certain features and services or restrict your access to parts or the entire Website without notice or liability at any time in the Operator's exclusive discretion, without prejudice to any legal or equitable remedies available to the Operators, for any reason or purpose, including, but not limited to, conduct that the Operators believe violates these Terms of Use or other policies or guidelines posted on the Website or conduct which the Operators believe is harmful to other customers, to the Operator's business, or to other information providers. In addition, this Agreement may be immediately terminated at any time by the Operators in their sole discretion. In addition and without prejudice to any other remedy available to the Operators, the Operators may immediately terminate this Agreement if you breach any term of this Agreement or other operating term set forth by the Operators.</p>
            
                <h2>10.  Access Under 16 Years of Age</h2>
                <p>Vixory’s services are not directed at children. Furthermore, we do not knowingly collect personal information from individuals under 16 years of age, unless consent is given or authorized by the holder of parental responsibility over the child. If we become aware that someone under 16 has provided us with personal details, we will take steps to delete such information. If you become aware that a child has unlawfully or unwittingly provided us with personal data, please contact our Support team.</p>

                <h2>11. Choice of Law; Jurisdiction; Attorneys' Fees</h2>
                <ul>
                    <li>This Agreement will be governed by the laws of the State of Missouri applicable to contracts entered into and performed exclusively in that State. Any court of competent jurisdiction sitting within Greene County, Missouri will be the exclusive jurisdiction and venue for any dispute arising out of or relating to this Agreement. You hereby waive any argument that any such court does not have jurisdiction over you or such dispute or that venue in any such court is not appropriate or convenient. The Operators will be entitled to recover their court costs and reasonable attorneys' fees and expenses incurred in successfully proving any breach of any term of this Agreement.</li>
                </ul>

                <h2>12. Miscellaneous</h2>
                <ul>
                    <li>This Agreement constitutes the entire agreement between the parties and supersedes all prior written or oral agreements or communications with respect to the subject matter herein. The Operators in their sole discretion may amend this Agreement, and your use of the Website after such amendment is posted on the Website will constitute acceptance of it by you. Sections 6, 7, 8, 10, 11 and 12 of this Agreement will survive any termination or cancellation of this Agreement. If any term in this Agreement is declared unlawful, void or for any reason unenforceable by any court, then such term will be deemed severable from the remaining terms and will not affect the validity and enforceability of such remaining terms. The section headings in this Agreement are for convenience only and must not be given any legal import.</li>
                </ul>

                <h2>13. Acceptance of Terms of Use</h2>
                <ul>
                    <li>By using the Website, you signify your agreement to the terms of this Agreement. If you do not agree to the terms in this Agreement, you must not use the Website. The Operators may change the terms of this Agreement at any time, and your use of the Website after such changes are posted will mean that you accept them.</li>
                </ul>

                <p class="font-bold">How To Contact</p>
                <p>The Website is operated and provided by Vixory LLC, 2733 E. Battlefield, Ste. 126, Springfield, Mo 65804. If you have questions about this Agreement, please contact us at <a class="accent" href="mailto:info@vixory.com">Info@Vixory.com</a></p>
            </div>
        </div>
    </PageWrapper>
</template>
<script>
export default {
    name:"TermsOfUse"
}
</script>
<style scoped>
.document p {
    margin-top:1em;
    margin-bottom:1em;
}
</style>